environment:
  window_size: [480, 480]
  traffic_density: 0.15
  stack_size: 4
  accident_prob: 0.8
  map: "SSTSSTSSTSSTSSTSST"
  need_inverse_traffic: True
  num_scenarios: 200
simulation:
  simulations_count: 1
  show_view: True
evaluation:
  policy_file: "models/chill-owl-867-1M.zip"
  # vit or resnet
  backbone: "vit"
  # resnet_features or vit_embeddings
  obs_feature_key: "vit_embeddings"
  just_embeddings: True
  num_episodes: 5
  show_view: True
seed: 1